# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: “http://github.com/zhanfangzxc”
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"


rss: /atom.xml


# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: ""
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true
#disqus_shortname: zhanfangzxc

#是否开启友情链接
#不开启——
#friends: true
#开启——
friends:
  马林康的博客: http://malinkang.com/

#是否开启“关于我”。
#不开启——
#aboutme: true
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…